# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c22370192a96b83f1539535c7c672e627b71b8a86fb53e2885ca0592b38492b945be3b8649df60b373e720cf8c839fe035fb4ad2ba36feaede9051e33bfd93

test:
  secret_key_base: b21e643ecd80026b86028a4e41017b631dbfa5770d9406176eb9e4169e677f0b4d7a0b1e2070fde7487efed4fd64bea168b375659e41cf0d60899f12a8409cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
